const fs=require('fs'),path=require('path'),matter=require('gray-matter'),{marked}=require('marked');
const R=__dirname,O=path.join(R,'dist'),S=JSON.parse(fs.readFileSync(path.join(R,'content/settings.json'),'utf8'));
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),ea=s=>esc(s).replace(/"/g,'&quot;');
const fmt=d=>new Date(d).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}),isoD=d=>new Date(d).toISOString().slice(0,10);
const load=d=>{const p=path.join(R,d);return fs.existsSync(p)?fs.readdirSync(p).filter(f=>f.endsWith('.md')).map(f=>{const g=matter(fs.readFileSync(path.join(p,f),'utf8'));return{...g.data,body:g.content,id:f.slice(0,-3)}}):[]};
const mailA=`<a href="mailto:${S.email}">${S.email}</a>`;
function render(md){let h=marked.parse(md||'');
h=h.replace(/<p><img([^>]*?)title="([^"]*)"([^>]*)><\/p>/g,'<figure><img$1$3 loading="lazy"><figcaption>$2</figcaption></figure>');
h=h.replace(/<blockquote>\s*<p><strong>([^<]*?):?<\/strong>/g,(m,l)=>`<blockquote class="note${/^İlginç/.test(l)?' fun':''}"><p><strong>${l}</strong>`);
let i=0;const toc=[];
h=h.replace(/<h2>(.*?)<\/h2>/g,(m,t)=>{const id='b'+i++;if(!/^Kaynakça$/i.test(t))toc.push([id,t]);return`<h2 id="${id}">${t}</h2>`});
h=h.replace(/<h2 id="(b\d+)">Kaynakça<\/h2>([\s\S]*)$/i,(m,id,r)=>`<section class="refs"><h2 id="${id}">Kaynakça</h2>${r}</section>`);
return{html:h.replace(/^<p>/,'<p class="lede">').replace(/\{mail\}/g,mailA),toc}}
const cats=load('content/categories').sort((a,b)=>(a.order??99)-(b.order??99));
const cat=id=>cats.find(c=>c.id==id)||{title:'',hue:30};
const posts=load('content/posts').filter(p=>!p.draft&&cats.some(c=>c.id==p.category)).sort((a,b)=>new Date(b.date)-new Date(a.date)).map(p=>({...p,...render(p.body),rt:Math.max(1,Math.round((p.body||'').split(/\s+/).length/200))}));
const u=p=>`/yazi/${p.id}/`,bg=id=>{const h=cat(id).hue??30;return`background:linear-gradient(135deg,hsl(${h} 38% 32%),hsl(${h} 32% 18%))`};
const w=(p,c)=>{const f=path.join(O,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const layout=({title,desc,p,body,type='website',extra=''})=>`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${ea(desc)}"><link rel="canonical" href="${S.siteUrl}${p}"><meta property="og:title" content="${ea(title)}"><meta property="og:description" content="${ea(desc)}"><meta property="og:type" content="${type}"><meta property="og:locale" content="tr_TR"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Merriweather:wght@400;700&display=swap"><link rel="stylesheet" href="/style.css">${extra}</head><body><header class="top"><div class="bar"><a class="logo" href="/">${esc(S.title)}<small>Tarih &amp; Derin Araştırma</small></a><nav aria-label="Ana menü"><details><summary>Kategoriler ▾</summary><div class="dd">${cats.map(c=>`<a href="/kategori/${c.id}/">${esc(c.title)}</a>`).join('')}</div></details></nav><form class="s" action="/arama/" role="search"><input name="q" type="search" placeholder="Yazılarda ara…" aria-label="Ara"><button>Ara</button></form></div></header><main>${body}</main><footer><div class="w"><a href="/hakkinda/">Hakkında</a><a href="/iletisim/">İletişim</a><a href="/gizlilik/">Gizlilik</a><br>© ${new Date().getFullYear()} ${esc(S.title)}</div></footer></body></html>`;
const card=p=>`<article class="card"><a class="img" href="${u(p)}" style="${p.image?`background:url(${p.image}) center/cover`:bg(p.category)}" aria-label="${ea(p.title)}">${p.image?'':esc(cat(p.category).title)}</a><div class="t"><div class="meta">${fmt(p.date)} · ${p.rt} dk okuma</div><h3><a href="${u(p)}">${esc(p.title)}</a></h3><p>${esc(p.excerpt)}</p></div></article>`;
fs.rmSync(O,{recursive:true,force:true});fs.cpSync(path.join(R,'static'),O,{recursive:true});
// ana sayfa
const hero=posts.find(p=>p.featured)||posts[0];
w('index.html',layout({title:`${S.title} — Tarih ve Derin Araştırma Blogu`,desc:S.description,p:'/',body:!hero?'<div class="w page"><h1>Henüz yazı yok</h1></div>':`<div class="w"><section class="hero"><div><div class="kick">Manşet · ${esc(cat(hero.category).title)}</div><h1>${esc(hero.title)}</h1><p class="lede">${esc(hero.excerpt)}</p><p class="meta">${fmt(hero.date)} · ${hero.rt} dk okuma</p><a class="btn" href="${u(hero)}">Okumaya Başla</a></div><a class="img" href="${u(hero)}" style="${hero.image?`background:url(${hero.image}) center/cover`:bg(hero.category)}" aria-label="${ea(hero.title)}">${hero.image?'':esc(cat(hero.category).title)}</a></section>${cats.filter(c=>posts.some(p=>p.category==c.id&&p!==hero)).map(c=>`<section class="sec"><h2>${esc(c.title)} <a href="/kategori/${c.id}/">Tümü →</a></h2><div class="grid">${posts.filter(p=>p.category==c.id&&p!==hero).slice(0,3).map(card).join('')}</div></section>`).join('')}</div>`}));
// kategoriler
for(const c of cats)w(`kategori/${c.id}/index.html`,layout({title:`${c.title} — ${S.title}`,desc:c.description||c.title,p:`/kategori/${c.id}/`,body:`<div class="w"><p class="crumb"><a href="/">Ana Sayfa</a> › Kategori</p><h1 style="margin-top:.4em">${esc(c.title)}</h1><p class="lede">${esc(c.description)}</p><div class="grid" style="padding-bottom:20px">${posts.filter(p=>p.category==c.id).map(card).join('')||'<p>Bu kategoride henüz yazı yok.</p>'}</div></div>`}));
// yazılar
for(const p of posts){const c=cat(p.category),rel=posts.filter(x=>x!==p&&x.category==p.category).concat(posts.filter(x=>x!==p&&x.category!=p.category)).slice(0,3);
const ld=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:p.title,datePublished:isoD(p.date),author:{'@type':'Person',name:p.author||S.author},description:p.excerpt||''}).replace(/</g,'\\u003c')}</script>`;
w(`yazi/${p.id}/index.html`,layout({title:`${p.title} — ${S.title}`,desc:p.excerpt||S.description,p:u(p),type:'article',extra:ld,body:`<div class="w"><p class="crumb"><a href="/">Ana Sayfa</a> › <a href="/kategori/${p.category}/">${esc(c.title)}</a></p><article class="post"><aside class="toc" aria-label="İçindekiler">${p.toc.length?`<b>İçindekiler</b>${p.toc.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}`:''}<p class="noprint"><button onclick="print()">PDF İndir / Yazdır</button></p></aside><div class="body"><header><div class="kick">${esc(c.title)}</div><h1>${esc(p.title)}</h1><p class="meta"><time datetime="${isoD(p.date)}">${fmt(p.date)}</time> · ${p.rt} dk okuma · Yazar: ${esc(p.author||S.author)}</p></header>${p.image?`<img class="cover" src="${p.image}" alt="">`:''}${p.html}</div></article>${rel.length?`<section class="sec"><h2>İlgili Yazılar</h2><div class="grid">${rel.map(card).join('')}</div></section>`:''}</div>`}))}
// kurumsal sayfalar
for(const id of ['hakkinda','gizlilik']){const g=load('content/pages').find(x=>x.id==id);if(g)w(`${id}/index.html`,layout({title:`${g.title} — ${S.title}`,desc:S.description,p:`/${id}/`,body:`<div class="w page"><h1>${esc(g.title)}</h1>${render(g.body).html}</div>`}))}
const inp=`<input type="hidden" name="form-name" value="contact"><p hidden><label>Bu alanı boş bırakın: <input name="bot-field"></label></p>`;
w('iletisim/index.html',layout({title:`İletişim — ${S.title}`,desc:'Okur ve tarihçilerden gelen mesajlar için iletişim formu.',p:'/iletisim/',body:`<div class="w page"><h1>İletişim</h1><p>Okur mesajları, düzeltme önerileri ve tarihçilerden gelen katkılar için: ${mailA}</p><form class="c" name="contact" method="POST" action="/tesekkurler/" data-netlify="true" netlify-honeypot="bot-field">${inp}<input name="ad" placeholder="Adınız" required><input name="eposta" type="email" placeholder="E-posta" required><input name="konu" placeholder="Konu" required><textarea name="mesaj" rows="6" placeholder="Mesajınız" required></textarea><div><button>Mesajı Gönder</button></div></form></div>`}));
w('tesekkurler/index.html',layout({title:`Teşekkürler — ${S.title}`,desc:'Mesajınız alındı.',p:'/tesekkurler/',body:'<div class="w page"><h1>Teşekkürler</h1><p>Mesajınız bize ulaştı. <a href="/">Ana sayfaya dön</a></p></div>'}));
w('arama/index.html',layout({title:`Arama — ${S.title}`,desc:'Sitede arama',p:'/arama/',extra:'<meta name="robots" content="noindex">',body:'<div class="w page" style="max-width:none"><h1 id="qs">Arama</h1><div id="res" class="grid"></div><script src="/search.js"></script></div>'}));
w('404.html',layout({title:`Sayfa bulunamadı — ${S.title}`,desc:'Sayfa bulunamadı',p:'/404.html',body:'<div class="w page"><h1>Sayfa bulunamadı</h1><p><a href="/">Ana sayfaya dön</a></p></div>'}));
w('search.json',JSON.stringify(posts.map(p=>({t:esc(p.title),e:esc(p.excerpt),u:u(p),c:esc(cat(p.category).title)}))));
const urls=['/',...cats.map(c=>`/kategori/${c.id}/`),...posts.map(u),'/hakkinda/','/iletisim/','/gizlilik/'];
w('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${S.siteUrl}${x}</loc></url>`).join('')}</urlset>`);
w('robots.txt',`User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ${S.siteUrl}/sitemap.xml\n`);
console.log(`Hazır: ${posts.length} yazı, ${cats.length} kategori → dist/`);
